# Generated by Django 5.2.1 on 2025-07-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deck_card_count_deck_description_deck_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='card_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
